name: TranslateThis
on:
    push:
        branches:
            - develop
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
           - name: Install Composer Dependencies
             working-directory: ./api-cer
             run: composer install --prefer-dist
            - run: docker build --target app -t joarariba/php-composer:1.2 -f ./php/Dockerfile .
            - run: docker build -t joarariba/nginx-php:1.0 -f ./nginx/Dockerfile .
            - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
            - run: docker push joarariba/php-composer:1.2
            - run: docker push joarariba/nginx-php:1.0